version: '3.8'
services:
  csvserver:
    image: infracloudio/csvserver:latest
    ports:
      - "9393:9300"
    environment:
      CSVSERVER_BORDER: Orange
    volumes:
      - ./inputFile:/csvserver/inputdata

  prometheus:
    image: prom/prometheus:v2.22.0
    ports:
      - "9090"
